version: "3.9"

services:
  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    image: zadanie-vizja-server:latest
    environment:
      - JAVA_OPTS=
      - SERVER_PORT=8080
      - SPRING_DATASOURCE_URL=jdbc:h2:file:./data/zadanievizja
      - SPRING_DATASOURCE_USERNAME=SA
      - SPRING_DATASOURCE_PASSWORD=
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
      - SPRING_H2_CONSOLE_ENABLED=true
    ports:
      - "8080:8080"
    volumes:
      - server-data:/app/data
    restart: unless-stopped

volumes:
  server-data:
