name: CI - Server and Client Tests

on:
  push:
    branches: [ "main" ]

jobs:
  server-tests:
    name: Server Tests (Maven)
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: server
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'
          cache: 'maven'

      - name: Cache Maven repository
        uses: actions/cache@v4
        with:
          path: |
            ~/.m2/repository
          key: ${{ runner.os }}-m2-${{ hashFiles('server/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-m2-

      - name: Run unit tests
        run: mvn -B -e -DskipITs test

  client-tests:
    name: Client Tests (Node)
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: client
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Use Node.js 20
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: client/package-lock.json

      - name: Install dependencies
        run: |
          if [ -f yarn.lock ]; then
            corepack enable
            yarn --version
            yarn install --frozen-lockfile
          else
            npm ci
          fi

      - name: Run tests
        env:
          CI: true
        run: |
          if [ -f yarn.lock ]; then
            yarn test --watchAll=false
          else
            npm test -- --watchAll=false
          fi
